---

-  hosts: all
   become: true
   tasks: 

   - name: install "{{ shraum }}" 
     yum: 
       update_cache: yes
       name: "{{ shraum }}"
       state: present
     when:  ansible_distribution == "Amazon" and ansible_distribution_version == "2"