---

- hosts: all
  become: true
  tasks: 

  - name: install apache(httpd) service 
    yum: 
      name: httpd
      state: present
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
           


