---

-  hosts: all
   become: true
   shraum: nginx
   dev: php
   tasks: 

   - name: install "{{shraum}}" and "{{dev}}" 
     yum: 
       update_cache: yes
       name: 
         - "{{shraum}}"
         - "{{dev}}"
       state: present
     when:  ansible_distribution == "Amazon" and ansible_distribution_version == "2"